wandb_version: 1

batch_size:
  desc: null
  value: 8
learning_rate:
  desc: null
  value: 1.0e-05
dropout:
  desc: null
  value: 0.05
gamma:
  desc: null
  value: 0.995
lambda:
  desc: null
  value: 1.0e-06
_wandb:
  desc: null
  value:
    python_version: 3.8.15
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1695725804.278627
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.8.15
      5: 0.15.4
      8:
      - 3
      - 5
